### ISSUE TITLE
import line from documentation does not work

### ISSUE THREAD

**Issue by RubenGarcia** [pipobscure/qrpng#2]
```
import qrcode from 'qrpng;
```
gives
```
Error TS1002: Unterminated string literal.
```
while
```
import * from 'qrpng';
```
gives
```
Error TS1005: 'as' expected.
```
and 
```
import { qrcode } from 'qrpng';
```
gives
```
Error TS2306: File '.../node_modules/qrpng/qr.d.ts' is not a module.
```

What is the correct way to use this module in TypeScript?

**Comment by pipobscure** [comment]
Appologies. I completely screwed up the types. Also excuse the late reply .I was not monitoring this repo.

The correct import should have been

```
import generateQR from 'qrpng';
```

**Comment by RubenGarcia** [comment]
Please reopen this until I have time to send a patch with the updated documentation
